# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PJLiveVideoPlaying' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PJLiveVideoPlaying
  
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'SJRouter'
  pod 'SJUIKit'
  pod 'SDWebImage'
  pod 'AFNetworking'
  pod 'SJVideoPlayer'

  
  pod 'SJBaseVideoPlayer/IJKPlayer'
  pod 'ijkplayerssl', :git => 'https://gitee.com/changsanjiang/ijkplayer.git'
  pod 'SJVideoPlayer'
  
  
  target 'PJLiveVideoPlayingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PJLiveVideoPlayingUITests' do
    # Pods for testing
  end

end
